-- Banco gerado a partir de Testes_eSales.xlsx
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `testes_esales` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `testes_esales`;

DROP TABLE IF EXISTS `testes_windows`;
CREATE TABLE `testes_windows` (
  `id_pk` INT AUTO_INCREMENT PRIMARY KEY,
  `id` INT,
  `teste_inicial_profissional_responsavel` VARCHAR(255),
  `iniciado` TINYINT(1),
  `c_2a_fase_testes_volumetria` VARCHAR(255),
  `resultado` VARCHAR(255),
  `clientes_utilizam_funcionalidade` VARCHAR(50),
  `nome_da_regra` VARCHAR(100),
  `configuracao_da_regra` VARCHAR(200),
  `executor_da_regra` VARCHAR(50),
  `tipo_de_regra` VARCHAR(50),
  `protocolo_parceiro` VARCHAR(50),
  `resultado_esperado` VARCHAR(200),
  `detalhamento_da_execucao_do_teste` TEXT,
  `resultado_obtido_com_1_arquivo_simples` VARCHAR(50),
  `resultado_obtido_com_1_arquivo_1gb` VARCHAR(50),
  `resultado_obtido_com_100_arquivos` VARCHAR(50),
  `resultado_obtido_com_5000_arquivos` VARCHAR(50),
  `versao_do_edie` VARCHAR(50),
  `build` VARCHAR(50),
  `issue` VARCHAR(255),
  `criticidade_issue` VARCHAR(255),
  `observacoes` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `testes_windows` (`id`, `teste_inicial_profissional_responsavel`, `iniciado`, `c_2a_fase_testes_volumetria`, `resultado`, `clientes_utilizam_funcionalidade`, `nome_da_regra`, `configuracao_da_regra`, `executor_da_regra`, `tipo_de_regra`, `protocolo_parceiro`, `resultado_esperado`, `detalhamento_da_execucao_do_teste`, `resultado_obtido_com_1_arquivo_simples`, `resultado_obtido_com_1_arquivo_1gb`, `resultado_obtido_com_100_arquivos`, `resultado_obtido_com_5000_arquivos`, `versao_do_edie`, `build`, `issue`, `criticidade_issue`, `observacoes`) VALUES
(1, NULL, 0, NULL, NULL, 'Correios', 'ESA 001 - RECEBE FTP COM DESCOMPATACAO', 'Excluir na origem / Compactar / Descompactar/MD5', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento e  descompactação e respeitando a integridades MD5', 'O arquivo trafegou compactado, chegando no destino descompactado, ao finalizar o trafego o arquivo compactado não foi excluido da origem.', 'Não se aplica', NULL, NULL, NULL, 'V_5.5', 2752.0, NULL, NULL, NULL),
(2, NULL, 0, NULL, NULL, 'Correios', 'ESA 002 - ENVIO FTP COM COMPATACAO', 'Excluir na origem / Compactar / Descompactar/MD5', '10.222.31.111', 'Envio', 'FTP', 'Fazer a compactação, enviar e respeitando a integridade MD5', 'O arquivo foi compactado e enviado ao diretório', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', 2752.0, NULL, NULL, NULL),
(4, NULL, 0, NULL, NULL, 'Correios', 'ESA 005 - ENVIA FTP PERCORRENDO SUBPASTAS', 'Excluir na origem / Não compactar / Percorrer subpastas; integridade; MD5/Manter Estrutura de Diretórios', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP percorrendo subpastas', 'O arquivo foi trafegado,chegando no destino porém, só ate a pasta que continha arquivos .', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', 2752.0, NULL, NULL, NULL),
(5, NULL, 0, NULL, NULL, 'Correios', 'ESA 006 - RECEBE FTP PERCORRENDO SUBPASTAS', 'Excluir na origem / Não compactar / Percorrer subpastas/Manter Estrutura de Diretórios', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP percorrendo subpastas', 'O arquivo foi recebido e entregue no subdiretório', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', 2752.0, NULL, NULL, NULL),
(6, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 007 - ENVIA FTP SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP sobrepondo o destino', 'O arquivo foi enviado e entregue no destino sobrepondo o mesmo', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', 2752.0, NULL, NULL, NULL),
(7, NULL, 0, NULL, NULL, 'Correios', 'ESA 008 - RECEBE FTP SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP sobrepondo o destino', 'O arquivo foi entregue no destino porém não sobrepôs o mesmo.', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', 2752.0, NULL, NULL, NULL),
(8, NULL, 0, NULL, NULL, 'Banestes', 'ESA 010 - ENVIA FTP COM MONITORAR', 'Excluir na origem / Não compactar / Monitorar', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP com monitor', 'Funcionalidade foi desabilitada temporariamente, devido a mal funcionamento da mesma. Foi retirado da tela para evitar suporte até solução da mesma.', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(9, NULL, 0, NULL, NULL, 'Outros', 'ESA 011 - ENVIO FTP COM COPIA LOCAL', 'Excluir na origem / Não compactar / Percorrer subpastas/Sobrepor no destino/Cópia local/Manter Estrutura de Cópia / Manter estrutura no Servidor', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP e cópia local', 'O arquivo foi enviado e feito uma cópia no diretório copia local', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', NULL, NULL, NULL, NULL),
(10, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 012 - ENVIO FTP COM RENOMEIO ', 'Excluir na origem / Não compactar/Renomeio aba Parceiros', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP e o renomeio ', 'O arquivo foi entregue com o renomeio no destino,  com sequencial até após a extensão do arquivo', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', NULL, NULL, NULL, NULL),
(11, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 013 - RECEBE FTP COM RENOMEIO', 'Excluir na origem / Não compactar/ Renomeio (Conversão)', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP e o renomeio ', 'O arquivo foi recebido com o renomeio correto no destino', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.3', NULL, NULL, NULL, NULL),
(12, NULL, 0, NULL, NULL, 'Banestes', 'ESA 014 - ENVIO FTP TRUNCAR NOME DO ARQUIVO', 'Excluir na origem / Não compactar/ Truncar (Parceiro)', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio do arquivo para o FTP com o nome truncado', 'Esta sendo feito o truncamento de forma correta, obedecendo a configuração da regra, onde foi realizado teste com 1,2 e 8 posições de truncamento, onde todos os arquivos foram  trafegados e retirados os caracteres conforme estabelecido', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(13, NULL, 0, NULL, NULL, 'Banestes', 'ESA 015 - RECEBE FTP TRUNCAR NOME DO ARQUIVO', 'Excluir na origem / Não compactar/Truncar (Parceiro)', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP truncar nome do arquivo', 'Arquivo foi trafegado e recepcionado com o truncamento correto.', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(16, NULL, 0, NULL, NULL, 'Correios', 'ESA 016 - LITE MOVER COM ERROS', 'Mover com erros, Excluir na Origem', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e mover com erros', 'Foi alterado a senha do usuario parceiro para gerar a exceção ', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, 'Não envia e não remove com erro. Log informa arquivo excluído da origem com sucesso.'),
(15, NULL, 0, NULL, NULL, 'Correios', 'ESA 016 - LITE MOVER COM ERROS	', 'Mover com erros, Excluir na Origem', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e mover com erros', 'Foi alterado a senha do usuario parceiro para gerar a exceção ', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(17, NULL, 0, NULL, NULL, 'Outros', 'ESA 017 - ENVIO LITE COM MASCARA DE EXCLUSAO', 'Excluir na origem / Não compactar / Mover arquivos da máscara de Exclusão', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio Lite com mascara de exclusão, mover os arquivos excluídos para o diretório previamente configurados.', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(18, NULL, 0, NULL, NULL, 'Outros', 'ESA 017 - RECEBE LITE COM MASCARA DE EXCLUSÃO', 'Excluir na origem / Não compactar', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o envio Lite com mascara de exclusão, mover os arquivos excluídos para o diretório previamente configurados.', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(19, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 018 - ENVIO LITE TAMANHO KBYTES', 'Excluir na origem / Não compactar/Tamanho Mínimo 10 Kbytes', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio somente de arquivos com o tamanho específicado', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, 'o sistema aceita uma margem e qualquer arquivo acima de ~9,5KB'),
(20, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 018 - RECEBE LITE TAMANHO KBYTES', 'Excluir na origem / Não compactar/Tamanho Máximo 40 Kbytes', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer recepção somente de arquivos com o tamanho específicado', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(23, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 022 - ENVIO LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Mantem estrutura subdiretórios', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e percorrer as subpastas e excluir na origem', 'Os arquivos foram enviandos com sucesso', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(24, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 022 - RECEBE LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Mantem estrutura subdiretórios', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e percorrer as subpastas, mantendo a estrutura dos subdiretórios', 'Os arquivos foram enviandos com sucesso, criando a estrutura de subdiretórios', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(25, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio sobrepondo no destino', 'Os arquivos foram enviandos com sucesso, sobrepondo o mesmo arquivo com conteúdo diferente no destino ', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(26, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 023 - LITE RECEBE SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor Localmente', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo sobrepondo o destino', 'Os arquivos foram enviandos com sucesso, sobrepondo o mesmo arquivo com conteúdo diferente no destino ', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(27, NULL, 0, NULL, NULL, 'Outros', 'ESA 025 - ENVIO LITE VERSIONAR', 'Excluir na origem / Não Compactar / versionar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo versionado', 'os arquivo foram transmitidos, mas não fez criação deixou o arquivo de versionamento na pasta no drive,', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(28, NULL, 0, NULL, NULL, 'Outros', 'ESA 025 - RECEBE LITE VERSIONAR', 'Excluir na origem / Não Compactar / versionar', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo versionado', 'os arquivo foram transmitidos, mas não fez criação deixou o arquivo de versionamento na pasta no drive,', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(29, NULL, 0, NULL, NULL, 'Banestes', 'ESA 026 - ENVIO LITE /MONITORAR', 'Excluir na origem, monitorar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo sem a necessidade de agendamento ou execução manual', 'Ao criar ou receber um arquivo em um diretório monitorado por uma regra com a funcionalidade de monitorar, o mesmo deve realizar automáticamente o envio do arquivo sem a necessidade de ter um agendamento ou uma execução manual.', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(30, NULL, 0, NULL, NULL, 'Banestes', 'ESA 026 - RECEBE LITE /MONITORAR', 'Excluir na origem, monitorar', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o envio do arquivo sem a necessidade de agendamento ou execução manual', 'Ao criar ou receber um arquivo em um diretório monitorado por uma regra com a funcionalidade de monitorar, o mesmo deve realizar automáticamente o envio do arquivo sem a necessidade de ter um agendamento ou uma execução manual.', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(31, NULL, 0, NULL, NULL, 'Correios', 'ESA 027 - ENVIO LITE COM COPIA', 'Excluir na origem / Percorrer subpastas / Sobrepor no Destino / Habilitar copia e manter estrutura', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo e uma cópia', 'Os arquivos foram enviandos com sucesso', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(32, NULL, 0, NULL, NULL, 'Correios', 'ESA 027 - RECEBE LITE COM COPIA', 'Excluir na origem / Percorrer subpastas / Sobrepor no Destino / Habilitar copia e manter estrutura', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo  e uma cópia', 'Não tem a função de cópia no protocolo de recepção', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(33, NULL, 0, NULL, NULL, 'Correios', 'ESA 028 - ENVIO LITE COM RENOMEIO', 'Excluir na origem / Não compactar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e renomeio do arquivo', 'Foi utilizado uma máscara de renomeio e inserida na regra de envio, onde os arquivos foram trafegados com sucesso e renomeados.', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(34, NULL, 0, NULL, NULL, 'Correios', 'ESA 028 - ENVIO LITE COM RENOMEIO', 'Excluir na origem / Não compactar', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e renomeio', 'Foi utilizado uma máscara de renomeio e inserida na regra de recebimento, onde os arquivos foram trafegados com sucesso e renomeados.', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(35, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', 'Excluir na origem / Não compactar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, 'Foi utilizado o comando Get-FileHash -Path ".\\arquivo.txt" -Algorithm MD5 |||| com powerhell, antes do envio, após enviar foi comparado o código gerado pelo comando e o CRC no tráfego analíco e foi constatados que ambos são idênticos, garantindo a integridade do arquivo'),
(36, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', 'Excluir na origem / Não compactar', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o recebimento com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, 'Foi utilizado o comando Get-FileHash -Path ".\\arquivo.txt" -Algorithm MD5 |||| com powerhell, antes do envio, após chegar na pasta de recepção foi comparado o código gerado pelo comando e o CRC no tráfego analíco e foi constatados que ambos são idênticos, garantindo a integridade do arquivo'),
(39, NULL, 0, NULL, NULL, 'Correios', 'ESA 032 - CXA COM MÁSCARA DE EXCLUSÃO', 'Não compactar', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer  o recebimento com máscara de exclusão', 'Deve-se colocar no diretório arquivos válidos e arquivos inválidos que no caso são arquivos com máscara *.txt, e assim somente devem ser trafegados todos os arquivos menos os da máscara de exclusão. O teste deve ser feito nos dois sentidos CXA->Server /Server->CXA', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(40, NULL, 0, NULL, NULL, 'Correios', 'ESA 033 - CXA COM TAMANHO MIN / MAXIMO', 'Não compactar', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento com  tamanho minimo e tamanho máximo', 'Arquivos sendo enviado/recebido conforme tamanho minimo e máximo estabelecido', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(42, NULL, 0, NULL, NULL, 'Correios', 'ESA 037 - CXA PERCORRER SUBPASTAS', 'Percorrer Subpastas', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e percorrer as subpastas', 'O arquivo foi recebido e percorrido a subpasta', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(44, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 039 - CXA SOBREPOR LOCALMENTE', 'Sobrepor Localmente', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e sobrepor localmente', 'O arquivo foi recebido e sobrepondo no destino', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(45, NULL, 0, NULL, NULL, 'Correios', 'ESA 042 - CXA COM RENOMEIO', 'CXA com renomeio', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento com renomeio', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, 'CLIENT CXA > SERVIDOR renomeio funciona normalemnte, SERVIDOR > CLIENT CXA não ocorre o renomeio'),
(47, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 044 - CXA COM COPIA NO CLIENT', 'Percorrer Subpastas', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e percorrer as subpastas', 'O arquivo foi recebido e percorrido a subpasta', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, 'Ao executar o client recebo o seguinte erro no log: ERROR - 16/01/2026 08:56:29.630 [10.222.31.112] - 500:  - br.com.esales.edienterprise.rest.response.RegraCaixaViewResponse@1d053a7c\nbr.com.esales.odette.exception.EdiException'),
(48, NULL, 0, NULL, NULL, 'Correios', 'ESA 045 - CXA BUSCA ARQUIVO NA RAIZ', 'CXA Busca arquivo na Raiz', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento busca arquivo na raiz', 'O arquivo foi recebido na pasta raiz. A regra não irá criar uma pasta de envio, todos os arquivos devem ser colocados no diretório de origem com o nome da regra, e para serem encontrados e enviados pelo EDI, devem possuir uma nomenclatura específica: nome do usuário para o qua foi utilizado o download do CXA seguido de #.', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(49, NULL, 0, NULL, NULL, 'Correios', 'ESA 046 - CXA COM INTEGRIDADE MD5', 'Percorrer Subpastas', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o envio com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(83, NULL, 0, NULL, NULL, 'Correios', 'ESA 048 - ENVIO FTPS PERCORRENDO SUBPASTA', 'Excluir na Origem / Percorrer subpastas', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio  percorrendo as pastas', 'O arquivo foi enviado e percorre as subpastas', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(50, NULL, 0, NULL, NULL, 'Correios', 'ESA 049 - SFTP COM MASCARA DE EXCLUSAO', 'Excluir na Origem / Máscara positiva / Máscara negativa / Mover para diretorio especifico', '10.222.31.112', 'Envio', 'SSH / SFTP', 'Fazer o envio da máscara positiva e movimentar o arquivo da máscara negativa excluindo todos os arquivos para diretorio', 'O arquivo foi enviado ao diretório e destino', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'V_5.1', '5.5.1_2973', NULL, NULL, NULL),
(52, NULL, 0, NULL, NULL, 'Correios', 'ESA 050 - SFTP TAMANHO MIN/MAX KB', 'Excluir na Origem', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio com tamanho maximo e minimo ', 'O arquivo foi enviado ao diretório e destino', 'A Realizar', 'A Realizar', NULL, NULL, 'V_5.1', '5.5.1_2973', NULL, NULL, 'não trafega 4GB, e só trafega até 3,5gb se aumentar para 30s nas tentativas'),
(54, NULL, 0, NULL, NULL, 'Correios', 'ESA 051 - SFTP MOVER COM ERROS', 'Mover com erros / Excluir na Origem', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio mover com erros e excluir na origem', 'O arquivo não está sendo enviado para pasta deerro ', NULL, NULL, NULL, NULL, 'V_5.1', '5.5.1_2973', NULL, NULL, 'Não trafega, só joga o arquivo bin p pasta de erro'),
(56, NULL, 0, NULL, NULL, 'Outros', 'ESA 052 - SFTP MOVER ARQ DA MASCARA DE EXCLUSAO', 'Excluir na Origem / Mover arquivos da máscara de exclusão para diretório', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e mover arquivo com máscara de exclusão', 'O arquivo foi enviado e feita a máscara de exclusão', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(61, NULL, 0, NULL, NULL, 'Correios', 'ESA 055 - SFTP PERCORRER SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e percorrer as subpastas', 'O arquivo foi enviado e perrcorreu a subpasta', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.1', '5.5.1_2973', NULL, NULL, NULL),
(63, NULL, 0, NULL, NULL, 'Correios', 'ESA 056 - SFTP SOBREPOR NO DESTINO', 'Excluir na Origem / Sobrepor o destino', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e sobrepor no destino', 'O arquivo foi enviado e sobrepondo no destino', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.1', '5.5.1_2973', NULL, NULL, NULL),
(65, NULL, 0, NULL, NULL, 'Banestes', 'ESA 058 - SFTP TMP NO DESTINO', 'Excluir na Origem / Habilitar .tmp recebendo no destino', '10.222.31.111', 'Envio', 'SSH / SFTP', 'É que seja criado .tmp no diretório de destino e somente após finalizado o recebimento a extensão do arquivo deve ser alterada', 'O arquivo foi enviado é criando o .tmp', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(67, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 060 - SFTP COM COPIA LOCAL', 'Excluir na origem / Sobrepor no destino / Habilitar cópia / Manter estrutura de cópia', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e cópia no diretório', 'O arquivo foi enviado e feito a copia', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, NULL),
(69, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 061 - SFTP COM RENOMEIO', 'Excluir na Origem, Renomeio', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e renomeio do arquivo', 'O arquivo foi enviado e feito o renomeio', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, NULL),
(71, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 062 - SFTP COM INTEGRIDADE MD5', 'Excluir na Origem, Verificação de integridade MD5', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio com integridade MD5', 'O arquivo foi enviado e feito a integridade MD5', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, 'Atquivo enviado porém sem confirmação de integridade em log'),
(73, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 063 - OFTP FORMATO ASCII 128 -> EBCDIC', 'Excluir na Origem', '10.222.31.112', 'Envio', 'OFTP-R', 'Fazer o envio o formato EBCDIC para ASCII 128', 'O arquivo foi enviado e convertido ao formato correto', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(76, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 064 - OFTP RECEBE COM RENOMEIO DE ARQUIVO', ' Renomeio do arquivo', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento com renomeio de arquivo', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(77, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 066 - OFTP COM CRLF ATIVO', 'Excluir na Origem / CRLF (Remover)', '10.222.31.112', 'Envio', 'OFTP-S', 'Fazer o envio com CRLF (remover), simulando o cliente Sabesp ', 'O arquivo foi enviado conforme o esperado e o CRLF removido, desde que o RVS esteja configurado corretamente na opção (record handling = VTXT_FBIN)', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(79, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 067 - OFTP ENVIO COM COPIA', 'Excluir na Origem / Copia local / Renomeio na copia', '10.222.31.112', 'Envio', 'OFTP-R', 'Fazer o envio com cópia', 'O arquivo foi enviado com cópia', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(87, NULL, 0, NULL, NULL, 'Banestes', 'ESA 070 - FTPS SOBREPOR NO DESTINO', 'Excluir / Sobrepor no destino', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio e sobrepor no destino', 'O arquivo foi enviado e sobrepondo no destino', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(89, NULL, 0, NULL, NULL, 'Correios', 'ESA 073 - FTPS COM COPIA LOCAL', 'Excluir na Origem / Percorrer Subpastas / Habilitar copia e manter estrutura', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio com copia local', 'O arquivo foi enviado e feita a copia no diretorio', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(91, NULL, 0, NULL, NULL, 'Correios', 'ESA 074 - FTPS MANTER ESTRUTURA DE PASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio manter estrutura de pastas', 'O arquivo foi enviado', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(93, NULL, 0, NULL, NULL, 'Correios', 'ESA 076 - FTPS COM CRIPTOGRAFIA MD5', 'Excluir na Origem/Verificação de integridade MD5', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio e respeitando a integridades MD5', 'O arquivo foi enviado com criptografia MD5', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(94, NULL, 0, NULL, NULL, 'Correios', 'ESA 077 - FTPS COM RENOMEIO', 'Excluir na Origem / Renomear o arquivo', '10.222.31.111', 'Envio', 'FTPS', 'Fazer o envio com renomeio de arquivo', 'O arquivo foi enviado e feito o renomeio', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(14, NULL, 0, NULL, NULL, 'Banestes / Sabesp', 'ESA 078 - RECEBE FTP COM COPIA REMOTA', 'Excluir na origem / Não compactar', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento do arquivo via FTP e fazer com cópia remota no servidor de FTP', 'O arquivo foi recebido e feito a copia remota no repositorio configurado', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(97, NULL, 0, NULL, NULL, 'Banestes', 'ESA 079 -BANESTES (BNT 002)- ENVIA FTP', 'Excluir na origem/ Sobrepor localmente/ Renomeio em Parceiro/ Modo de Transferencia Ascii/ Utilizar caracter temporario', '10.222.31.112', 'Envio', 'FTP', 'Fazer o envio de um arquivo para servidor FTP utilizando a transferencia ASCII e caracter temporario ', 'O arquivo foi enviado para servidor FTP, respeitando as configurações da regra', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(96, NULL, 0, NULL, NULL, 'Banestes', 'ESA 080  - RECEBE FTP EXPRESSAO REGULAR ', 'Excluir na origem/ Sobrepor localmente/ Expressão Regular (mascaras e diretórios)/ Copia Local/ Copia Remota/ Modo de Transferencia Ascii', '10.222.31.112', 'Recepção', 'FTP', 'Fazer o recebimento de um arquivo utilizando expressão regular', 'O arquivo foi recebido corretamente , respeitando a expressão regular', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(98, NULL, 0, NULL, NULL, 'Banestes', 'ESA 081 -  RECEBE FTP MULTIPLO DIRETORIO', 'Excluir na origem/ Sobrepor localmente/ Multiplos Diretórios (mascaras e diretórios)/ Copia Local/ Mascara de Renomeio (Conversao)/Copia Remota/ Modo de Transferencia Ascii', '10.222.31.112', 'Recepção', 'FTP', 'Fazer o recebimento somente do arquivo de acordo com a mascara configurada no multiplos diretório utilizando conversao / copia remota / modo de transferencia ASCII', 'O arquivo foi recebido em multiplo diretorio ', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(99, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 082 - ENVIO LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA DOS SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Não mantem estrutura subdiretórios', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e percorrer as subpastas e excluir na origem', 'Os arquivos foram enviandos com sucesso e excluio na origem', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(100, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 082 - RECEBE LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Não mantem estrutura subdiretórios', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e percorrer as subpastas, sem manter a estrutura dos subdiretórios', 'Os arquivos foram enviandos com sucesso, sem criar a estrutura de subdiretórios', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(104, NULL, 0, NULL, NULL, 'Banestes', 'ESA 083 - ENVIA COM ANALYZER', 'Excluir na origem / Sobrepor no destino/ Manter Estrutura/ Percorrer subpasta / Inclusão de conteudo do arquivo na nomenclatura', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(106, NULL, 0, NULL, NULL, 'Todos', 'ESA 085 - AGENDAMENTO RECEBE FTP', 'Excluir na origem / Sobrepor no destino / Renomeio', '10.222.31.111', 'Recepção', 'FTP', 'Enviar os arquivos exluindo na origem e renomeando no destino', 'Os arquivos foram enviandos com sucesso excluidos na origem e renomeados no destino', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(101, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 086 AGENDAMENTO - GOVSC ENVIA -> ESLOVENIA OFTP', 'Excluir na origem / Sobrepor no destino', '10.222.31.112', 'Envio', 'OFTP-R', 'Enviar os arquivos para o servidor OFTP', 'Ao forçar um erro, nesse caso o usuário está alterado, o arquivo é excluído da origem mesmo que tenha ocorrido erros', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(107, NULL, 0, NULL, NULL, 'Outros', 'ESA 087 - ALERTA ARQUIVO PARADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(84, NULL, 0, NULL, NULL, 'Correios', 'ESA 088 - ENVIO FTPS PERCORRENDO SUBPASTA', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento e percorrer Subpastas', 'O arquivo foi recebido e percorre as subpastas', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(51, NULL, 0, NULL, NULL, 'Correios', 'ESA 089 - SFTP COM MASCARA DE EXCLUSAO', 'Excluir na Origem / Máscara positiva / Máscara negativa / Mover para diretorio especifico', '10.222.31.112', 'Recepção', 'SSH / SFTP', 'Fazer o envio da máscara positiva no diretorio', 'O arquivo foi recebido ao diretório de destino', NULL, NULL, NULL, NULL, 'V_4.11', '5.5.1_2973', NULL, NULL, NULL),
(53, NULL, 0, NULL, NULL, 'Correios', 'ESA 090 - SFTP TAMANHO MIN/MAX KB', 'Excluir na Origem', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento com tamanho maximo e minimo', 'O arquivo foi recebido ao diretório de destino', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, 'Trafegou somente 1,5gb, Não executou o renomeio remoto e não excluiu da origem'),
(55, NULL, 0, NULL, NULL, 'Correios', 'ESA 091 - SFTP MOVER COM ERROS', 'Mover com erros / Excluir na Origem', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento mover com erros e excluir na origem', 'O arquivo não está sendo recebido para pasta de erro', NULL, NULL, NULL, NULL, 'V_4.11', '5.5.1_2973', NULL, NULL, NULL),
(62, NULL, 0, NULL, NULL, 'Correios', 'ESA 092 - SFTP PERCORRER SUBPASTAS E ENVIAR PARA MULTIPLOS DIRETORIOS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e percorrer as subpastas - além de entregar o mesmo arquivo em mais de um diretório', 'O arquivo foi recebido e perrcorreu a subpasta - entregou em mais de um diretório', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, NULL),
(64, NULL, 0, NULL, NULL, 'Correios', 'ESA 093 - SFTP SOBREPOR NO DESTINO', 'Excluir na Origem / Sobrepor Localmente', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e sobrepor no destino', 'O arquivo foi recebido e sobrepondo no destino', 'A Realizar', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, NULL),
(66, NULL, 0, NULL, NULL, 'Outros', 'ESA 094 - SFTP TMP NO DESTINO', 'Excluir na Origem / Habilitar .tmp recebendo no destino', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento', 'O arquivo foi recebido', 'Efetuado com sucesso', NULL, NULL, NULL, 'V_5.2.1', 2667.0, NULL, NULL, NULL),
(68, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 095 - SFTP COM COPIA LOCAL', 'Excluir na Origem / Sobrepor Localmente', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e cópia no diretório', 'O arquivo foi recebido e feito a copia', NULL, NULL, NULL, NULL, 'V_4.11', '5.5.1_2973', NULL, NULL, NULL),
(70, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 096 - SFTP COM RENOMEIO E COPIA REMOTA', 'Excluir na Origem, Renomeio', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento, renomeio do arquivo e copia remota do arquivo ', 'O arquivo foi recebido, feito a copia e feito o renomeio', NULL, NULL, NULL, NULL, 'V_4.11', '5.5.1_2973', NULL, NULL, 'não renomeia @suf, não gera cópia em dir FTP, nada em log'),
(72, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 097 - SFTP COM INTEGRIDADE MD5', 'Excluir na Origem, Verificação de integridade MD5', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento com integridade MD5', 'O arquivo foi recebido feito a integridade MD5', 'Efetuado com sucesso', 'Efetuado com sucesso', NULL, NULL, 'V_5.2.1', '5.5.1_2973', NULL, NULL, 'Atquivo enviado porém sem confirmação de integridade em log'),
(74, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 098 - OFTP FORMATO EBCDIC -> ASCII', 'Excluir na Origem', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento do arquivo, convertendo de  ASCII 128 para EBCDIC ', 'O arquivo foi recebido, porém não foi convertido ao formato correto, além de não ter sido excluído da origem.', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(80, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 099 - OFTP RECEBE COM COPIA', 'Excluir na Origem / Copia local / Renomeio na copia', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento com cópia', 'O arquivo foi recebido somente em um dos diretórios apontados ', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(88, NULL, 0, NULL, NULL, 'Correios', 'ESA 100 - FTPS SOBREPOR NO DESTINO', 'Excluir / Sobrepor localmente', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento e sobrepor localmente', 'O arquivo foi recebido e sobrepondo no destino', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(92, NULL, 0, NULL, NULL, 'Correios', 'ESA 101 - FTPS MANTER ESTRUTURA DE PASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento manter estrutura de pastas', 'O arquivo foi recebido', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(95, NULL, 0, NULL, NULL, 'Correios', 'ESA 102 - FTPS COM RENOMEIO', 'Excluir na Origem / Renomear o arquivo', '10.222.31.111', 'Recepção', 'FTPS', 'Fazer o recebimento com renomeio de arquivo', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(108, NULL, 0, NULL, NULL, 'Banestes / / Correios', 'ESA 105 - EXPURGO DE ARQUIVOS 35 DIAS', 'Agendamento de limpeza', '10.222.31.112', NULL, NULL, 'Exclusão de arquivos criados no período maior de 35 dias', 'Foi criado um agendamento de limpeza para exclusão de arquivos criado no período maior que 35 dias', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, 'Banestes / / Correios', 'ESA 107 - EXPURGO ARQ. MAIOR QUE 1000000KB', 'Agendamento de limpeza', '10.222.31.112', NULL, NULL, 'Exclusão de arquivos criados maior que 1000000 Bytes', 'Foi criado um agendamento de limpeza para arquivos maiores de 1000000 Bytes', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(109, NULL, 0, NULL, NULL, 'Banestes / / Correios', 'ESA 106 - EXPURGO DE ARQUIVOS 20 DIAS', 'Agendamento de limpeza', '10.222.31.112', NULL, NULL, 'Exclusão de arquivos criados no período maior de 20 dias', 'Foi criado um agendamento de limpeza para exclusão de arquivos criado no período maior que 20 dias', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(110, NULL, 0, NULL, NULL, 'Todos', 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Envio', 'EDIE Lite', 'Fazer o envio e pecorrer subpastas', 'O arquivo foi enviado e perrcorreu a subpasta', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(111, NULL, 0, NULL, NULL, 'Todos', 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e sem manter a estrutura', 'O arquivo foi recebido e não manteve a subpasta', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL),
(112, NULL, 0, NULL, NULL, 'Banestes', 'ESA 108 - ENCADEAMENTO DE REGRAS', 'Excluir na Origem / Sobrepor Localmente / Mascara Positiva', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento do arquivo de acordo com a mascara', 'Criado um par de regras e conectar a regra de envio na regra de recepção para ser executada automaticamente após a recepção do arquivo', 'Efetuado com sucesso', 'A Realizar', 'Efetuado com sucesso', NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(113, NULL, 0, NULL, NULL, 'Banestes', 'ESA 109 - ENCADEAMENTO DE REGRAS', 'Excluir na Origem / Sobrepor Localmente / Mascara de Renomeio / Cópia Local ', '10.222.31.111', 'Envio', 'FTP', 'Fazer o recebimento do arquivo de acordo com a mascara', 'Criado um par de regras e conectar a regra de envio na regra de recepção para ser executada automaticamente após a recepção do arquivo', 'Efetuado com sucesso', 'A Realizar', 'Efetuado com sucesso', NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(114, NULL, 0, NULL, NULL, 'Banestes', 'ESA * - TESTE HTTP SEM SOBREPOR ATIVADO', NULL, '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o envio do arquivo, e após a segunda tentiva, deve ser exibida mensagem de erro na aplicação e no relatório analítico', 'Deve ser realizado o trafego de um arquivo via http por uma regra CXA, sem o sobrepor está ativado, e após o primeiro trafego, deve ser relizado novamente o trafego do mesmo arquivo', NULL, NULL, NULL, NULL, 'V_5.1', NULL, NULL, NULL, NULL),
(114, NULL, 0, NULL, NULL, NULL, 'ESA 111 - Validação CHave RSA', NULL, NULL, NULL, NULL, 'Fazer os testes com a criação e uso da chave RSA ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(115, NULL, 0, NULL, NULL, 'Correios', 'ESA 112 - ENVIA LITE MULTIPLOS DIRETORIOS', NULL, NULL, NULL, NULL, 'Fazer o envio de um mesmo arquivo para diretórios diferentes.', 'Deve ser colocado um arquivo no diretório de origem e esse arquivo deve ser entregue em 2 ou mais diretórios de forma identica.', NULL, NULL, NULL, NULL, 'V_4.11', NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `testes_linux`;
CREATE TABLE `testes_linux` (
  `id_pk` INT AUTO_INCREMENT PRIMARY KEY,
  `id` INT,
  `teste_inicial_profissional_responsavel` VARCHAR(255),
  `iniciado` TINYINT(1),
  `c_2a_fase_testes_volumetria` VARCHAR(255),
  `resultado` VARCHAR(255),
  `clientes_utilizam_funcionalidade` VARCHAR(50),
  `nome_da_regra` VARCHAR(100),
  `configuracao_da_regra` VARCHAR(200),
  `executor_da_regra` VARCHAR(50),
  `tipo_de_regra` VARCHAR(50),
  `protocolo_parceiro` VARCHAR(50),
  `resultado_esperado` VARCHAR(200),
  `detalhamento_da_execucao_do_teste` TEXT,
  `resultado_obtido_com_1_arquivo_simples` VARCHAR(50),
  `resultado_obtido_com_1_arquivo_1gb` VARCHAR(50),
  `resultado_obtido_com_100_arquivos` VARCHAR(50),
  `resultado_obtido_com_5000_arquivos` VARCHAR(50),
  `versao_do_edie` VARCHAR(50),
  `build` INT,
  `issue` VARCHAR(50),
  `criticidade_issue` VARCHAR(50),
  `observacoes` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `testes_linux` (`id`, `teste_inicial_profissional_responsavel`, `iniciado`, `c_2a_fase_testes_volumetria`, `resultado`, `clientes_utilizam_funcionalidade`, `nome_da_regra`, `configuracao_da_regra`, `executor_da_regra`, `tipo_de_regra`, `protocolo_parceiro`, `resultado_esperado`, `detalhamento_da_execucao_do_teste`, `resultado_obtido_com_1_arquivo_simples`, `resultado_obtido_com_1_arquivo_1gb`, `resultado_obtido_com_100_arquivos`, `resultado_obtido_com_5000_arquivos`, `versao_do_edie`, `build`, `issue`, `criticidade_issue`, `observacoes`) VALUES
(1, NULL, 0, NULL, NULL, 'Correios', 'LINUX - ESA 001 - RECEBE FTP COM DESCOMPATACAO', 'Excluir na origem / Compactar / Descompactar/MD5', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento e  descompactação e respeitando a integridades MD5', 'O arquivo trafegou compactado, chegando no destino e descompactou na pasta TEMP do EDIE, deixando os mesmos la.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, NULL, 0, NULL, NULL, 'Correios', 'ESA 002 - ENVIO FTP COM COMPATACAO', 'Excluir na origem / Compactar / Descompactar/MD5', '10.222.31.111', 'Envio', 'FTP', 'Fazer a compactação e enviar e respeitando a integridade MD5', 'O arquivo foi compactado e enviado ao diretório', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, NULL, 0, NULL, NULL, 'Correios', 'ESA 005 - ENVIA FTP PERCORRENDO SUBPASTAS', 'Excluir na origem / Não compactar / Percorrer subpastas; integridade; MD5/Manter Estrutura de Diretórios', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP percorrendo subpastas', 'O arquivo foi enviado e entregue no subdiretório, usando MD5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, NULL, 0, NULL, NULL, 'Correios', 'ESA 006 - ENVIA FTP PERCORRENDO SUBPASTAS', 'Excluir na origem / Não compactar / Percorrer subpastas/Manter Estrutura de Diretórios', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP percorrendo subpastas', 'O arquivo foi recebido e entregue no subdiretório', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 007 - ENVIA FTP SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', NULL, 'Envio', 'FTP', 'Fazer o envio FTP sobrepondo o destino', 'O arquivo foi enviado e entregue no destino sobrepondo o mesmo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, NULL, 0, NULL, NULL, 'Correios', 'ESA 008 - RECEBE FTP SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', '10.222.31.111', 'Recepção', 'FTP', 'Fazer o recebimento FTP sobrepondo o destino', 'O arquivo foi entregue no destino sobrepondo o mesmo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, NULL, 0, NULL, NULL, 'Banestes', 'ESA 010 - ENVIA FTP COM MONITORAR', 'Excluir na origem / Não compactar / Monitorar', NULL, 'Envio', 'FTP', 'Fazer o envio FTP com monitor', 'Funcionalidade foi desabilitada temporariamente, devido a mal funcionamento da mesma. Foi retirado da tela para evitar suporte até solução da mesma.', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', '4.4.0.0', 4528, NULL, NULL, 'Verificação com Tribo File Transfer. Aguardando a reativação da funcionalidade com o recurso funcionando como esperado. Cliente Banestes vai utilizar da funcionalidade no fututo. Aguardando prioridade da tribo.'),
(9, NULL, 0, NULL, NULL, 'Correios', 'ESA 011 - ENVIO FTP COM COPIA LOCAL', 'Excluir na origem / Não compactar / Percorrer subpastas/Sobrepor no destino/Cópia local/Manter Estrutura de Cópia / Manter estrutura no Servidor', '10.222.31.111', 'Envio', 'FTP', 'Fazer o envio FTP e cópia local', 'O arquivo foi enviado e feito uma cópia no diretório copia local', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 012 - ENVIO FTP COM RENOMEIO ', 'Excluir na origem / Não compactar/Renomeio aba Parceiros', NULL, 'Envio', 'FTP', 'Fazer o envio FTP e o renomeio ', 'O arquivo foi entregue com o renomeio no destino,  com sequencial até após a extensão do arquivo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 013 - RECEBE FTP COM RENOMEIO', 'Excluir na origem / Não compactar/ Renomeio (Conversão)', NULL, 'Recepção', 'FTP', 'Fazer o recebimento FTP e o renomeio ', 'O arquivo foi recebido com o renomeio correto no destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, NULL, 0, NULL, NULL, 'Banestes', 'ESA 014 - ENVIO FTP TRUNCAR NOME DO ARQUIVO', 'Excluir na origem / Não compactar/ Truncar (Parceiro)', NULL, 'Envio', 'FTP', 'Fazer o envio do arquivo para o FTP com o nome truncado', 'Esta sendo feito o truncamento de forma incorreta, esta duplicando as posições. Se coloco truncar uma posição, o EDIE esta entendendo como 2 posições.', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, NULL),
(13, NULL, 0, NULL, NULL, 'Banestes', 'ESA 015 - RECEBE FTP TRUNCAR NOME DO ARQUIVO', 'Excluir na origem / Não compactar/Truncar (Parceiro)', NULL, 'Recepção', 'FTP', 'Fazer o recebimento FTP truncar nome do arquivo', 'Arquivo foi trafegado e recepcionado com o truncamento correto.', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, 'No log não aparece o truncamento do arquivo, mas no relatorio analitico esta OK e no repositório tambem.'),
(16, NULL, 0, NULL, NULL, 'Correios', 'ESA 016 - LITE MOVER COM ERROS', 'Mover com erros, Excluir na Origem', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e mover com erros', 'Foi alterado a senha do usuario parceiro para gerar a exceção ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, NULL, 0, NULL, NULL, 'Correios', 'ESA 016 - LITE MOVER COM ERROS	', 'Mover com erros, Excluir na Origem', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e mover com erros', 'Foi alterado a senha do usuario parceiro para gerar a exceção ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, NULL, 0, NULL, NULL, 'Banestes / / Correios', 'ESA 017 - ENVIO LITE COM MASCARA DE EXCLUSAO', 'Excluir na origem / Não compactar / Mover arquivos da máscara de Exclusão', NULL, 'Envio', 'EDIE Lite', 'Fazer o envio Lite com mascara de exclusão, mover os arquivos excluídos para o diretório previamente configurados.', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, NULL, 0, NULL, NULL, 'Banestes / / Correios', 'ESA 017 - RECEBE LITE COM MASCARA DE EXCLUSÃO', 'Excluir na origem / Não compactar', NULL, 'Recepção', 'EDIE Lite', 'Fazer o envio Lite com mascara de exclusão, mover os arquivos excluídos para o diretório previamente configurados.', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 018 - ENVIO LITE TAMANHO KBYTES', 'Excluir na origem / Não compactar/Tamanho Mínimo 10 Kbytes', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio somente de arquivos com o tamanho específicado', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 018 - RECEBE LITE TAMANHO KBYTES', 'Excluir na origem / Não compactar/Tamanho Máximo 40 Kbytes', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer recepção somente de arquivos com o tamanho específicado', 'os arquivos enviados são conforme descrito na regra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 022 - ENVIO LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Mantem estrutura subdiretórios', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e percorrer as subpastas e excluir na origem', 'Os arquivos foram enviandos com sucesso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 022 - RECEBE LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Mantem estrutura subdiretórios', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e percorrer as subpastas, mantendo a estrutura dos subdiretórios', 'Os arquivos foram enviandos com sucesso, criando a estrutura de subdiretórios', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor no destino', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio sobrepondo no destino', 'Os arquivos foram enviandos com sucesso, sobrepondo o mesmo arquivo com conteúdo diferente no destino ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', 'Excluir na origem / Não compactar / Sobrepor Localmente', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo sobrepondo o destino', 'Os arquivos foram enviandos com sucesso, sobrepondo o mesmo arquivo com conteúdo diferente no destino ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 025 - ENVIO LITE VERSIONAR', 'Excluir na origem / Não Compactar / versionar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo versionado', 'os arquivo foram transmitidos, mas não fez criação deixou o arquivo de versionamento na pasta no drive,', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.5.0.0', 4279, NULL, NULL, NULL),
(28, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 025 - RECEBE LITE VERSIONAR', 'Excluir na origem / Não Compactar / versionar', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo versionado', 'os arquivo foram transmitidos, mas não fez criação deixou o arquivo de versionamento na pasta no drive,', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.5.0.0', 4279, NULL, NULL, NULL),
(29, NULL, 0, NULL, NULL, 'Banestes', 'ESA 026 - ENVIO LITE /MONITORAR', 'Excluir na origem, monitorar', NULL, 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo sem a necessidade de agendamento ou execução manual', 'Ao criar ou receber um arquivo em um diretório monitorado por uma regra com a funcionalidade de monitorar, o mesmo deve realizar automáticamente o envio do arquivo sem a necessidade de ter um agendamento ou uma execução manual.', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', '4.4.0.0', 4528, NULL, NULL, 'Em contato com a tribo, ficou acertado a inclusão novamente da funcionalidade após a implementação do módulo de auditoria.'),
(30, NULL, 0, NULL, NULL, 'Banestes', 'ESA 026 - RECEBE LITE /MONITORAR', 'Excluir na origem, monitorar', NULL, 'Recepção', 'EDIE Lite', 'Fazer o envio do arquivo sem a necessidade de agendamento ou execução manual', 'Ao criar ou receber um arquivo em um diretório monitorado por uma regra com a funcionalidade de monitorar, o mesmo deve realizar automáticamente o envio do arquivo sem a necessidade de ter um agendamento ou uma execução manual.', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', 'Funcionalidade removida', '4.4.0.0', 4528, NULL, NULL, 'Em contato com a tribo, ficou acertado a inclusão novamente da funcionalidade após a implementação do módulo de auditoria.'),
(31, NULL, 0, NULL, NULL, 'Correios', 'ESA 027 - ENVIO LITE COM COPIA', 'Excluir na origem / Percorrer subpastas / Sobrepor no Destino / Habilitar copia e manter estrutura', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio do arquivo e uma cópia', 'Os arquivos foram enviandos com sucesso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, NULL, 0, NULL, NULL, 'Correios', 'ESA 027 - RECEBE LITE COM COPIA', 'Excluir na origem / Percorrer subpastas / Sobrepor no Destino / Habilitar copia e manter estrutura', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento do arquivo  e uma cópia', 'Os arquivos foram enviandos com sucesso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, NULL, 0, NULL, NULL, 'Correios', 'ESA 028 - ENVIO LITE COM RENOMEIO', 'Excluir na origem / Não compactar', '10.222.31.112', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e renomeio', 'Foi utilizado uma máscara de renomeio e inserida na regra de recebimento, onde os arquivos foram trafegados com sucesso e renomeados.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, NULL, 0, NULL, NULL, 'Correios', 'ESA 028 - ENVIO LITE COM RENOMEIO', 'Excluir na origem / Não compactar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e renomeio do arquivo', 'Foi utilizado uma máscara de renomeio e inserida na regra de envio, onde os arquivos foram trafegados com sucesso e renomeados.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', 'Excluir na origem / Não compactar', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(36, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', 'Excluir na origem / Não compactar', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o recebimento com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(39, NULL, 0, NULL, NULL, 'Correios', 'ESA 032 - CXA COM MÁSCARA DE EXCLUSÃO', 'Não compactar', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer  o recebimento com máscara de exclusão', 'Deve-se colocar no diretório arquivos válidos e arquivos inválidos que no caso são arquivos com máscara *.txt, e assim somente devem ser trafegados todos os arquivos menos os da máscara de exclusão. O teste deve ser feito nos dois sentidos CXA->Server /Server->CXA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(40, NULL, 0, NULL, NULL, 'Correios', 'ESA 033 - CXA COM TAMANHO MIN / MAXIMO', 'Não compactar', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento com  tamanho minimo e tamanho máximo', 'Arquivos sendo enviado/recebido conforme tamanho minimo e máximo estabelecido', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(42, NULL, 0, NULL, NULL, 'Correios', 'ESA 037 - CXA PERCORRER SUBPASTAS', 'Percorrer Subpastas', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e percorrer as subpastas', 'O arquivo foi recebido e percorrido a subpasta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(44, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 039 - CXA SOBREPOR LOCALMENTE', 'Sobrepor Localmente', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e sobrepor localmente', 'O arquivo foi recebido e sobrepondo no destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(45, NULL, 0, NULL, NULL, 'Correios', 'ESA 042 - CXA COM RENOMEIO', 'CXA com renomeio', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento com renomeio', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(47, NULL, 0, NULL, NULL, 'Banestes / Correios', 'ESA 044 - CXA COM COPIA NO CLIENT', 'Percorrer Subpastas / Habilitar prefixo nos arquivos ', NULL, 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento e percorrer as subpastas', 'O arquivo foi recebido e percorrido a subpasta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(48, NULL, 0, NULL, NULL, 'Correios', 'ESA 045 - CXA BUSCA ARQUIVO NA RAIZ', 'CXA Busca arquivo na Raiz', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o recebimento busca arquivo na raiz', 'O arquivo foi recebido na pasta raiz. A regra não irá criar uma pasta de envio, todos os arquivos devem ser colocados no diretório de origem com o nome da regra, e para serem encontrados e enviados pelo EDI, devem possuir uma nomenclatura específica: nome do usuário para o qua foi utilizado o download do CXA seguido de #.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(49, NULL, 0, NULL, NULL, 'Correios', 'ESA 046 - CXA COM INTEGRIDADE MD5', 'Percorrer Subpastas', '10.222.31.111', 'Recepção', '@EDIE Lite -CXA', 'Fazer o envio com integridade MD5', 'Deve ser feita a verificação do hash do arquivo antes do envio, para isso pode ser utilizado o notepad++ na aba tools MD5, e após conferir o hash do arquivo deve enviar via EDIE e conferir o CRC nos relatórios para conferir se é o mesmo anteriormente gerado.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(83, NULL, 0, NULL, NULL, 'Correios', 'ESA 048 - ENVIO FTPS PERCORRENDO SUBPASTA', 'Excluir na Origem / Percorrer subpastas', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio  percorrendo as pastas', 'O arquivo foi enviado e percorre as subpastas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50, NULL, 0, NULL, NULL, 'Correios', 'ESA 049 - SFTP COM MASCARA DE EXCLUSAO', 'Excluir na Origem / Máscara positiva / Máscara negativa / Mover para diretorio especifico', '10.222.31.112', 'Envio', 'SSH / SFTP', 'Fazer o envio da máscara positiva e movimentar o arquivo da máscara negativa excluindo todos os arquivos para diretorio', 'O arquivo foi enviado ao diretório e destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(52, NULL, 0, NULL, NULL, 'Correios', 'ESA 050 - SFTP TAMANHO MIN/MAX KB', 'Excluir na Origem', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio com tamanho maximo e minimo ', 'O arquivo foi enviado ao diretório e destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(54, NULL, 0, NULL, NULL, 'Correios', 'ESA 051 - SFTP MOVER COM ERROS', 'Mover com erros / Excluir na Origem', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio mover com erros e excluir na origem', 'O arquivo não está sendo enviado para pasta deerro ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(56, NULL, 0, NULL, NULL, 'Outros', 'ESA 052 - SFTP MOVER ARQ DA MASCARA DE EXCLUSAO', 'Excluir na Origem / Mover arquivos da máscara de exclusão para diretório', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e mover arquivo com máscara de exclusão', 'O arquivo foi enviado e feita a máscara de exclusão', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.5.0.0', 4296, NULL, NULL, 'É utilizados com outros protocolos nos clientes.'),
(61, NULL, 0, NULL, NULL, 'Correios', 'ESA 055 - SFTP PERCORRER SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e percorrer as subpastas', 'O arquivo foi enviado e perrcorreu a subpasta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(63, NULL, 0, NULL, NULL, 'Correios', 'ESA 056 - SFTP SOBREPOR NO DESTINO', 'Excluir na Origem / Sobrepor o destino', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e sobrepor no destino', 'O arquivo foi enviado e sobrepondo no destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(65, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 058 - SFTP TMP NO DESTINO', 'Excluir na Origem / Habilitar .tmp recebendo no destino', '10.222.31.111', 'Envio', 'SSH / SFTP', 'É que seja criado .tmp no diretório de destino e somente após finalizado o recebimento a extensão do arquivo deve ser alterada', 'O arquivo foi enviado é criando o .tmp', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4319, 'https://kallxtech.atlassian.net/browse/FILE-684', 'Aprovada', 'Alterar a extensão original do arquivo para *.tmp enquanto o mesmo está sendo gravado no SFTP de destino e voltar o arquivo para a extensão original quando o envio for concluído, na mesma sessão.'),
(67, NULL, 0, NULL, NULL, 'Correios', 'ESA 060 - SFTP COM COPIA LOCAL', 'Excluir na origem / Sobrepor no destino / Habilitar cópia / Manter estrutura de cópia', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e cópia no diretório', 'O arquivo foi enviado e feito a copia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(69, NULL, 0, NULL, NULL, 'Correios', 'ESA 061 - SFTP COM RENOMEIO', 'Excluir na Origem, Renomeio', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio e renomeio do arquivo', 'O arquivo foi enviado e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(71, NULL, 0, NULL, NULL, 'Correios', 'ESA 062 - SFTP COM INTEGRIDADE MD5', 'Excluir na Origem, Verificação de integridade MD5', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio com integridade MD5', 'O arquivo foi enviado e feito a integridade MD5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(73, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 063 - OFTP FORMATO ASCII 128 -> EBCDIC', 'Excluir na Origem', '10.222.31.112', 'Envio', 'OFTP-R', 'Fazer o envio o formato EBCDIC para ASCII 128', 'O arquivo foi enviado e convertido ao formato correto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(76, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 064 - OFTP RECEBE COM RENOMEIO DE ARQUIVO', ' Renomeio do arquivo', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento com renomeio de arquivo', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(77, NULL, 0, NULL, NULL, 'Correios', 'ESA 066 - OFTP COM CRLF ATIVO', 'Excluir na Origem / CRLF (Remover)', '10.222.31.112', 'Envio', 'OFTP-S', 'Fazer o envio com CRLF (remover), simulando o cliente Sabesp ', 'O arquivo foi enviado conforme o esperado e o CRLF removido, desde que o RVS esteja configurado corretamente na opção (record handling = VTXT_FBIN)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(79, NULL, 0, NULL, NULL, 'Correios', 'ESA 067 - OFTP ENVIO COM COPIA', 'Excluir na Origem / Copia local / Renomeio na copia', '10.222.31.112', 'Envio', 'OFTP-R', 'Fazer o envio com cópia', 'O arquivo foi enviado com cópia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(87, NULL, 0, NULL, NULL, 'Banestes', 'ESA 070 - FTPS SOBREPOR NO DESTINO', 'Excluir / Sobrepor no destino', NULL, 'Envio', 'FTPS', 'Fazer o envio e sobrepor no destino', 'O arquivo foi enviado e sobrepondo no destino', 'Efetuado com sucesso', NULL, NULL, NULL, '4.4.0.0', 4528, NULL, NULL, NULL),
(89, NULL, 0, NULL, NULL, 'Correios', 'ESA 073 - FTPS COM COPIA LOCAL', 'Excluir na Origem / Percorrer Subpastas / Habilitar copia e manter estrutura', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio com copia local', 'O arquivo foi enviado e feita a copia no diretorio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(91, NULL, 0, NULL, NULL, 'Correios', 'ESA 074 - FTPS MANTER ESTRUTURA DE PASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio manter estrutura de pastas', 'O arquivo foi enviado', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(93, NULL, 0, NULL, NULL, 'Correios', 'ESA 076 - FTPS COM CRIPTOGRAFIA MD5', 'Excluir na Origem/Verificação de integridade MD5', '10.222.31.112', 'Envio', 'FTPS', 'Fazer o envio e respeitando a integridades MD5', 'O arquivo foi enviado com criptografia MD5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(94, NULL, 0, NULL, NULL, 'Correios', 'ESA 077 - FTPS COM RENOMEIO', 'Excluir na Origem / Renomear o arquivo', '10.222.31.111', 'Envio', 'FTPS', 'Fazer o envio com renomeio de arquivo', 'O arquivo foi enviado e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, NULL, 0, NULL, NULL, 'Banestes / Sabesp', 'ESA 078 - RECEBE FTP COM COPIA REMOTA', 'Excluir na origem / Não compactar', NULL, 'Recepção', 'FTP', 'Fazer o recebimento do arquivo via FTP e fazer com cópia remota no servidor de FTP', 'O arquivo foi recebido e feito a copia remota no repositorio configurado', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, 'Em determinado momento do teste, não estava trafegando todos os arquivos , apresentava erro: Erro executando copia de arquivos para os destinos apos download/ Erro executando ações apos download. Somente ao dar play e realizar uma nova comunicação que funciona.'),
(97, NULL, 0, NULL, NULL, 'Banestes', 'ESA 079 -BANESTES (BNT 002)- ENVIA FTP', 'Excluir na origem/ Sobrepor localmente/ Renomeio em Parceiro/ Modo de Transferencia Ascii/ Utilizar caracter temporario', NULL, 'Envio', 'FTP', 'Fazer o envio de um arquivo para servidor FTP utilizando a transferencia ASCII e caracter temporario ', 'O arquivo foi enviado para servidor FTP, respeitando as configurações da regra', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, 'Conforme verificado a regra está sobrepondo os arquivos, após uma análise foi alterado o tempo de execução da regra para o máximo de 1 arquivos simultâneos para contorno, no Banestes hoje são apenas 9 arquivos recebidos por dia.'),
(96, NULL, 0, NULL, NULL, 'Banestes', 'ESA 080  - RECEBE FTP EXPRESSAO REGULAR ', 'Excluir na origem/ Sobrepor localmente/ Expressão Regular (mascaras e diretórios)/ Copia Local/ Copia Remota/ Modo de Transferencia Ascii', NULL, 'Recepção', 'FTP', 'Fazer o recebimento de um arquivo utilizando expressão regular', 'O arquivo foi recebido corretamente , respeitando a expressão regular', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, NULL),
(98, NULL, 0, NULL, NULL, 'Banestes', 'ESA 081 -  RECEBE FTP MULTIPLO DIRETORIO', 'Excluir na origem/ Sobrepor localmente/ Multiplos Diretórios (mascaras e diretórios)/ Copia Local/ Mascara de Renomeio (Conversao)/Copia Remota/ Modo de Transferencia Ascii', NULL, 'Recepção', 'FTP', 'Fazer o recebimento somente do arquivo de acordo com a mascara configurada no multiplos diretório utilizando conversao / copia remota / modo de transferencia ASCII', 'O arquivo foi recebido em multiplo diretorio ', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, 'Ocorreu um problema durante o trafego que nao consegui reproduzir de nov. Tinha um agendamento de uma regra de FTP executando a cada 1 minuto, quando startava esta regra, apresentava somente: Regra 613 já esta em execução.... So executou quando parei o agendamento. Quando startei de novo, funcionou os dois juntos. Tirando isso, os arquivos chegaram quando usa multiplos diretorios com mascaras distintas e com mascaras iguais'),
(99, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 082 - ENVIO LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA DOS SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Não mantem estrutura subdiretórios', '10.222.31.111', 'Envio', 'EDIE Lite', 'Fazer o envio e percorrer as subpastas e excluir na origem', 'Os arquivos foram enviandos com sucesso e excluio na origem', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(100, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 082 - RECEBE LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA SUBDIRETORIOS', 'Excluir na origem / Não compactar / Percorrer subpastas / Não mantem estrutura subdiretórios', '10.222.31.111', 'Recepção', 'EDIE Lite', 'Fazer o recebimento e percorrer as subpastas, sem manter a estrutura dos subdiretórios', 'Os arquivos foram enviandos com sucesso, sem criar a estrutura de subdiretórios', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(104, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 083 - ENVIA COM ANALYZER', 'Excluir na origem / Sobrepor no destino/ Manter Estrutura/ Percorrer subpasta / Inclusão de conteudo do arquivo na nomenclatura', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(106, NULL, 0, NULL, NULL, 'Todos', 'ESA 085 - AGENDAMENTO RECEBE FTP', 'Excluir na origem / Sobrepor no destino / Renomeio', NULL, 'Recepção', 'FTP', 'Enviar os arquivos exluindo na origem e renomeando no destino', 'Os arquivos foram enviandos com sucesso excluidos na origem e renomeados no destino', NULL, NULL, NULL, NULL, '4.4.0.0', NULL, NULL, NULL, NULL),
(101, NULL, 0, NULL, NULL, 'Correios', 'ESA 086 AGENDAMENTO - GOVSC ENVIA -> ESLOVENIA OFTP', 'Excluir na origem / Sobrepor no destino', '10.222.31.112', 'Envio', 'OFTP-R', 'Enviar os arquivos para o servidor OFTP', 'Ao forçar um erro, nesse caso o usuário está alterado, o arquivo é excluído da origem mesmo que tenha ocorrido erros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(107, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 087 - ALERTA ARQUIVO PARADO', NULL, NULL, NULL, NULL, NULL, NULL, 'Efetuado com sucesso', NULL, NULL, 'Não se aplica', '4.4.0.0', 4325, 'https://kallxtech.atlassian.net/browse/FILE-1382', 'Aprovada', 'Aguardando correção'),
(84, NULL, 0, NULL, NULL, 'Correios', 'ESA 088 - ENVIO FTPS PERCORRENDO SUBPASTA', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento e percorrer Subpastas', 'O arquivo foi recebido e percorre as subpastas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(51, NULL, 0, NULL, NULL, 'Correios', 'ESA 089 - SFTP COM MASCARA DE EXCLUSAO', 'Excluir na Origem / Máscara positiva / Máscara negativa / Mover para diretorio especifico', '10.222.31.112', 'Recepção', 'SSH / SFTP', 'Fazer o envio da máscara positiva no diretorio', 'O arquivo foi recebido ao diretório de destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(53, NULL, 0, NULL, NULL, 'Correios', 'ESA 090 - SFTP TAMANHO MIN/MAX KB', 'Excluir na Origem', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento com tamanho maximo e minimo', 'O arquivo foi recebido ao diretório de destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(55, NULL, 0, NULL, NULL, 'Correios', 'ESA 091 - SFTP MOVER COM ERROS', 'Mover com erros / Excluir na Origem', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento mover com erros e excluir na origem', 'O arquivo não está sendo recebido para pasta de erro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(62, NULL, 0, NULL, NULL, 'Correios', 'ESA 092 - SFTP PERCORRER SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e percorrer as subpastas', 'O arquivo foi recebido e perrcorreu a subpasta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(64, NULL, 0, NULL, NULL, 'Correios', 'ESA 093 - SFTP SOBREPOR NO DESTINO', 'Excluir na Origem / Sobrepor Localmente', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e sobrepor no destino', 'O arquivo foi recebido e sobrepondo no destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(66, NULL, 0, NULL, NULL, 'Sabesp', 'ESA 094 - SFTP TMP NO DESTINO', 'Excluir na Origem / Habilitar .tmp recebendo no destino', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento', 'O arquivo foi recebido', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4319, NULL, NULL, NULL),
(68, NULL, 0, NULL, NULL, 'Correios', 'ESA 095 - SFTP COM COPIA LOCAL', 'Excluir na Origem / Sobrepor Localmente', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e cópia no diretório', 'O arquivo foi recebido e feito a copia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(70, NULL, 0, NULL, NULL, 'Correios', 'ESA 096 - SFTP COM RENOMEIO', 'Excluir na Origem, Renomeio', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento e renomeio do arquivo', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(72, NULL, 0, NULL, NULL, 'Correios / TSE', 'ESA 097 - SFTP COM INTEGRIDADE MD5', 'Excluir na Origem, Verificação de integridade MD5', '10.222.31.111', 'Recepção', 'SSH / SFTP', 'Fazer o recebimento com integridade MD5', 'O arquivo foi recebido feito a integridade MD5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(74, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 098 - OFTP FORMATO EBCDIC -> ASCII', 'Excluir na Origem', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento do arquivo, convertendo de  ASCII 128 para EBCDIC ', 'O arquivo foi recebido, porém não foi convertido ao formato correto, além de não ter sido excluído da origem.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(80, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 099 - OFTP RECEBE COM COPIA', 'Excluir na Origem / Copia local / Renomeio na copia', '10.222.31.112', 'Recepção', 'OFTP-R', 'Fazer o recebimento com cópia', 'O arquivo foi recebido somente em um dos diretórios apontados ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(88, NULL, 0, NULL, NULL, 'Correios', 'ESA 100 - FTPS SOBREPOR NO DESTINO', 'Excluir / Sobrepor localmente', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento e sobrepor localmente', 'O arquivo foi recebido e sobrepondo no destino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(92, NULL, 0, NULL, NULL, 'Correios', 'ESA 101 - FTPS MANTER ESTRUTURA DE PASTAS', 'Excluir na Origem / Percorrer Subpastas', '10.222.31.112', 'Recepção', 'FTPS', 'Fazer o recebimento manter estrutura de pastas', 'O arquivo foi recebido', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(95, NULL, 0, NULL, NULL, 'Correios', 'ESA 102 - FTPS COM RENOMEIO', 'Excluir na Origem / Renomear o arquivo', '10.222.31.111', 'Recepção', 'FTPS', 'Fazer o recebimento com renomeio de arquivo', 'O arquivo foi recebido e feito o renomeio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(108, NULL, 0, NULL, NULL, 'Correios', 'ESA 105 - EXPURGO DE ARQUIVOS 35 DIAS', 'Agendamento de limpeza', NULL, NULL, NULL, 'Exclusão de arquivos criados no período maior de 35 dias', 'Foi criado um agendamento de limpeza para exclusão de arquivos criado no período maior que 35 dias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, 'Correios', 'ESA 107 - EXPURGO ARQ. MAIOR QUE 1000000KB', 'Agendamento de limpeza', NULL, NULL, NULL, 'Exclusão de arquivos criados maior que 1000000 Bytes', 'Foi criado um agendamento de limpeza para arquivos maiores de 1000000 Bytes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(109, NULL, 0, NULL, NULL, 'Correios / ', 'ESA 106 - EXPURGO DE ARQUIVOS 20 DIAS', 'Agendamento de limpeza', NULL, NULL, NULL, 'Exclusão de arquivos criados no período maior de 20 dias', 'Foi criado um agendamento de limpeza para exclusão de arquivos criado no período maior que 20 dias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(110, NULL, 0, NULL, NULL, 'Todos', 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', NULL, 'Envio', 'EDIE Lite', 'Fazer o envio e pecorrer subpastas', 'O arquivo foi enviado e perrcorreu a subpasta', NULL, NULL, NULL, NULL, '4.4.0.0', NULL, NULL, NULL, NULL),
(111, NULL, 0, NULL, NULL, 'Todos', 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', 'Excluir na Origem / Percorrer Subpastas', NULL, 'Recepção', 'EDIE Lite', 'Fazer o recebimento e sem manter a estrutura', 'O arquivo foi recebido e não manteve a subpasta', NULL, NULL, NULL, NULL, '4.4.0.0', NULL, NULL, NULL, NULL),
(112, NULL, 0, NULL, NULL, 'Banestes', 'ESA 108 - ENCADEAMENTO DE REGRAS', 'Excluir na Origem / Sobrepor Localmente / Mascara Positiva', NULL, 'Recepção', 'FTP', 'Fazer o recebimento do arquivo de acordo com a mascara', NULL, 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, NULL),
(113, NULL, 0, NULL, NULL, 'Banestes', 'ESA 109 - ENCADEAMENTO DE REGRAS', 'Excluir na Origem / Sobrepor Localmente / Mascara de Renomeio / Cópia Local ', NULL, 'Envio', 'FTP', NULL, NULL, 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, NULL),
(114, NULL, 0, NULL, NULL, NULL, 'ESA - ? teste do NFS - Comportamento com um diretorio inexistente ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(115, NULL, 0, NULL, NULL, 'Banestes / Sabesp', 'ESA 110 - ENVIO SSH CHAVE PUBLICA/PRIVADA', 'Excluir na Origem/', '10.222.31.111', 'Envio', 'SSH / SFTP', 'Fazer o envio dos arquivos utilizando chave publica e privada ', NULL, 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', 'Efetuado com sucesso', '4.4.0.0', 4528, NULL, NULL, NULL),
(116, NULL, 0, NULL, NULL, NULL, 'ESA 111 - RECEPCAO SSH CHAVE PUBLICA/PRIVADA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, NULL, 'ESA ? - Regra Analyzer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, NULL, 'ESA 092 - SFTP PERCORRER SUBPASTAS E ENVIAR PARA MULTIPLOS DIRETORIOS (ESPELHAR WINDOWS)', NULL, NULL, NULL, NULL, NULL, 'REGRA WINDOWS COM PROBLEMA (FAZER OUTRA)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, NULL, 'ESA 096 - SFTP COM RENOMEIO E COPIA REMOTA (ESPELHAR)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, 0, NULL, NULL, NULL, 'ESA 108 - ENCADEAMENTO DE REGRAS ( Espelhar )', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

DROP TABLE IF EXISTS `regras_reprovadas`;
CREATE TABLE `regras_reprovadas` (
  `id_pk` INT AUTO_INCREMENT PRIMARY KEY,
  `localizacao` VARCHAR(255),
  `id` VARCHAR(255),
  `nome_da_regra` VARCHAR(255),
  `resultado` VARCHAR(255),
  `criticidade` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `listas`;
CREATE TABLE `listas` (
  `id_pk` INT AUTO_INCREMENT PRIMARY KEY,
  `resultado` VARCHAR(50),
  `tipo_de_regra` VARCHAR(50),
  `protocolo` VARCHAR(50),
  `resultado_esperado` VARCHAR(50),
  `criticidade` VARCHAR(50),
  `clientes` VARCHAR(50),
  `profissionais` VARCHAR(50),
  `executor` VARCHAR(50),
  `versao_edie` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `listas` (`resultado`, `tipo_de_regra`, `protocolo`, `resultado_esperado`, `criticidade`, `clientes`, `profissionais`, `executor`, `versao_edie`) VALUES
('Aprovado', 'Envio', 'FTP', 'Efetuado com sucesso', 'Bloqueante', 'Banestes', 'Gustavo Lucena', '10.222.31.111', 'V_4.11'),
('Reprovado', 'Recepção', 'EDIE Lite', 'Efetuado com erro', 'Não Bloqueante', 'Banestes / Correios', 'Matheus Carvalho', '10.222.31.112', 'V_4.12'),
('Em Andamento', NULL, '@EDIE Lite -CXA', 'A Realizar', 'Aprovada', 'Banestes / Sabesp', 'Leilson Pereira', '10.222.31.130', 'V_4.13'),
('Aguardando Ação', NULL, 'SSH / SFTP', 'Funcionalidade removida', NULL, 'Banestes / TSE', 'Moises Oliveira', '10.222.31.139', 'V_4.14'),
('Volumetria', NULL, 'OFTP-S', 'Não se aplica', NULL, 'Correios', 'Julliana Leão', NULL, 'V_5.1'),
('Não Iniciado', NULL, 'OFTP-R', NULL, NULL, 'Correios / TSE', 'Thiago Cardozo', NULL, 'V_5.2.1'),
(NULL, NULL, 'FTPS', NULL, NULL, 'Sabesp', 'Vinicius Moraes', NULL, 'V_5.3'),
(NULL, NULL, NULL, NULL, NULL, 'Sabesp / TSE', NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, 'TSE', NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, 'Theke', NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, 'Todos', NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, 'Outros', NULL, NULL, NULL);

DROP TABLE IF EXISTS `engine`;
CREATE TABLE `engine` (
  `id_pk` INT AUTO_INCREMENT PRIMARY KEY,
  `origem` VARCHAR(50),
  `id` INT,
  `nome` VARCHAR(100),
  `resultado` VARCHAR(255),
  `criticidade` VARCHAR(50),
  `flag` INT,
  `matchno` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `engine` (`origem`, `id`, `nome`, `resultado`, `criticidade`, `flag`, `matchno`) VALUES
('Windows', 1, 'ESA 001 - RECEBE FTP COM DESCOMPATACAO', NULL, NULL, 0, NULL),
('Windows', 2, 'ESA 002 - ENVIO FTP COM COMPATACAO', NULL, NULL, 0, NULL),
('Windows', 4, 'ESA 005 - ENVIA FTP PERCORRENDO SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 5, 'ESA 006 - RECEBE FTP PERCORRENDO SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 6, 'ESA 007 - ENVIA FTP SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 7, 'ESA 008 - RECEBE FTP SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 8, 'ESA 010 - ENVIA FTP COM MONITORAR', NULL, NULL, 0, NULL),
('Windows', 9, 'ESA 011 - ENVIO FTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Windows', 10, 'ESA 012 - ENVIO FTP COM RENOMEIO ', NULL, NULL, 0, NULL),
('Windows', 11, 'ESA 013 - RECEBE FTP COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 12, 'ESA 014 - ENVIO FTP TRUNCAR NOME DO ARQUIVO', NULL, NULL, 0, NULL),
('Windows', 13, 'ESA 015 - RECEBE FTP TRUNCAR NOME DO ARQUIVO', NULL, NULL, 0, NULL),
('Windows', 16, 'ESA 016 - LITE MOVER COM ERROS', NULL, NULL, 0, NULL),
('Windows', 15, 'ESA 016 - LITE MOVER COM ERROS	', NULL, NULL, 0, NULL),
('Windows', 17, 'ESA 017 - ENVIO LITE COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Windows', 18, 'ESA 017 - RECEBE LITE COM MASCARA DE EXCLUSÃO', NULL, NULL, 0, NULL),
('Windows', 19, 'ESA 018 - ENVIO LITE TAMANHO KBYTES', NULL, NULL, 0, NULL),
('Windows', 20, 'ESA 018 - RECEBE LITE TAMANHO KBYTES', NULL, NULL, 0, NULL),
('Windows', 23, 'ESA 022 - ENVIO LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Windows', 24, 'ESA 022 - RECEBE LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Windows', 25, 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 26, 'ESA 023 - LITE RECEBE SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 27, 'ESA 025 - ENVIO LITE VERSIONAR', NULL, NULL, 0, NULL),
('Windows', 28, 'ESA 025 - RECEBE LITE VERSIONAR', NULL, NULL, 0, NULL),
('Windows', 29, 'ESA 026 - ENVIO LITE /MONITORAR', NULL, NULL, 0, NULL),
('Windows', 30, 'ESA 026 - RECEBE LITE /MONITORAR', NULL, NULL, 0, NULL),
('Windows', 31, 'ESA 027 - ENVIO LITE COM COPIA', NULL, NULL, 0, NULL),
('Windows', 32, 'ESA 027 - RECEBE LITE COM COPIA', NULL, NULL, 0, NULL),
('Windows', 33, 'ESA 028 - ENVIO LITE COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 34, 'ESA 028 - ENVIO LITE COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 35, 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Windows', 36, 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Windows', 39, 'ESA 032 - CXA COM MÁSCARA DE EXCLUSÃO', NULL, NULL, 0, NULL),
('Windows', 40, 'ESA 033 - CXA COM TAMANHO MIN / MAXIMO', NULL, NULL, 0, NULL),
('Windows', 42, 'ESA 037 - CXA PERCORRER SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 44, 'ESA 039 - CXA SOBREPOR LOCALMENTE', NULL, NULL, 0, NULL),
('Windows', 45, 'ESA 042 - CXA COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 47, 'ESA 044 - CXA COM COPIA NO CLIENT', NULL, NULL, 0, NULL),
('Windows', 48, 'ESA 045 - CXA BUSCA ARQUIVO NA RAIZ', NULL, NULL, 0, NULL),
('Windows', 49, 'ESA 046 - CXA COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Windows', 83, 'ESA 048 - ENVIO FTPS PERCORRENDO SUBPASTA', NULL, NULL, 0, NULL),
('Windows', 50, 'ESA 049 - SFTP COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Windows', 52, 'ESA 050 - SFTP TAMANHO MIN/MAX KB', NULL, NULL, 0, NULL),
('Windows', 54, 'ESA 051 - SFTP MOVER COM ERROS', NULL, NULL, 0, NULL),
('Windows', 56, 'ESA 052 - SFTP MOVER ARQ DA MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Windows', 61, 'ESA 055 - SFTP PERCORRER SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 63, 'ESA 056 - SFTP SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 65, 'ESA 058 - SFTP TMP NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 67, 'ESA 060 - SFTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Windows', 69, 'ESA 061 - SFTP COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 71, 'ESA 062 - SFTP COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Windows', 73, 'ESA 063 - OFTP FORMATO ASCII 128 -> EBCDIC', NULL, NULL, 0, NULL),
('Windows', 76, 'ESA 064 - OFTP RECEBE COM RENOMEIO DE ARQUIVO', NULL, NULL, 0, NULL),
('Windows', 77, 'ESA 066 - OFTP COM CRLF ATIVO', NULL, NULL, 0, NULL),
('Windows', 79, 'ESA 067 - OFTP ENVIO COM COPIA', NULL, NULL, 0, NULL),
('Windows', 87, 'ESA 070 - FTPS SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 89, 'ESA 073 - FTPS COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Windows', 91, 'ESA 074 - FTPS MANTER ESTRUTURA DE PASTAS', NULL, NULL, 0, NULL),
('Windows', 93, 'ESA 076 - FTPS COM CRIPTOGRAFIA MD5', NULL, NULL, 0, NULL),
('Windows', 94, 'ESA 077 - FTPS COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 14, 'ESA 078 - RECEBE FTP COM COPIA REMOTA', NULL, NULL, 0, NULL),
('Windows', 97, 'ESA 079 -BANESTES (BNT 002)- ENVIA FTP', NULL, NULL, 0, NULL),
('Windows', 96, 'ESA 080  - RECEBE FTP EXPRESSAO REGULAR ', NULL, NULL, 0, NULL),
('Windows', 98, 'ESA 081 -  RECEBE FTP MULTIPLO DIRETORIO', NULL, NULL, 0, NULL),
('Windows', 99, 'ESA 082 - ENVIO LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA DOS SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Windows', 100, 'ESA 082 - RECEBE LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Windows', 104, 'ESA 083 - ENVIA COM ANALYZER', NULL, NULL, 0, NULL),
('Windows', 106, 'ESA 085 - AGENDAMENTO RECEBE FTP', NULL, NULL, 0, NULL),
('Windows', 101, 'ESA 086 AGENDAMENTO - GOVSC ENVIA -> ESLOVENIA OFTP', NULL, NULL, 0, NULL),
('Windows', 107, 'ESA 087 - ALERTA ARQUIVO PARADO', NULL, NULL, 0, NULL),
('Windows', 84, 'ESA 088 - ENVIO FTPS PERCORRENDO SUBPASTA', NULL, NULL, 0, NULL),
('Windows', 51, 'ESA 089 - SFTP COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Windows', 53, 'ESA 090 - SFTP TAMANHO MIN/MAX KB', NULL, NULL, 0, NULL),
('Windows', 55, 'ESA 091 - SFTP MOVER COM ERROS', NULL, NULL, 0, NULL),
('Windows', 62, 'ESA 092 - SFTP PERCORRER SUBPASTAS E ENVIAR PARA MULTIPLOS DIRETORIOS', NULL, NULL, 0, NULL),
('Windows', 64, 'ESA 093 - SFTP SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 66, 'ESA 094 - SFTP TMP NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 68, 'ESA 095 - SFTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Windows', 70, 'ESA 096 - SFTP COM RENOMEIO E COPIA REMOTA', NULL, NULL, 0, NULL),
('Windows', 72, 'ESA 097 - SFTP COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Windows', 74, 'ESA 098 - OFTP FORMATO EBCDIC -> ASCII', NULL, NULL, 0, NULL),
('Windows', 80, 'ESA 099 - OFTP RECEBE COM COPIA', NULL, NULL, 0, NULL),
('Windows', 88, 'ESA 100 - FTPS SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Windows', 92, 'ESA 101 - FTPS MANTER ESTRUTURA DE PASTAS', NULL, NULL, 0, NULL),
('Windows', 95, 'ESA 102 - FTPS COM RENOMEIO', NULL, NULL, 0, NULL),
('Windows', 108, 'ESA 105 - EXPURGO DE ARQUIVOS 35 DIAS', NULL, NULL, 0, NULL),
('Windows', NULL, 'ESA 107 - EXPURGO ARQ. MAIOR QUE 1000000KB', NULL, NULL, 0, NULL),
('Windows', 109, 'ESA 106 - EXPURGO DE ARQUIVOS 20 DIAS', NULL, NULL, 0, NULL),
('Windows', 110, 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 111, 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', NULL, NULL, 0, NULL),
('Windows', 112, 'ESA 108 - ENCADEAMENTO DE REGRAS', NULL, NULL, 0, NULL),
('Windows', 113, 'ESA 109 - ENCADEAMENTO DE REGRAS', NULL, NULL, 0, NULL),
('Windows', 114, 'ESA * - TESTE HTTP SEM SOBREPOR ATIVADO', NULL, NULL, 0, NULL),
('Windows', 114, 'ESA 111 - Validação CHave RSA', NULL, NULL, 0, NULL),
('Windows', 115, 'ESA 112 - ENVIA LITE MULTIPLOS DIRETORIOS', NULL, NULL, 0, NULL),
('Linux', 1, 'LINUX - ESA 001 - RECEBE FTP COM DESCOMPATACAO', NULL, NULL, 0, NULL),
('Linux', 2, 'ESA 002 - ENVIO FTP COM COMPATACAO', NULL, NULL, 0, NULL),
('Linux', 4, 'ESA 005 - ENVIA FTP PERCORRENDO SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 5, 'ESA 006 - ENVIA FTP PERCORRENDO SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 1, 'ESA 007 - ENVIA FTP SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 7, 'ESA 008 - RECEBE FTP SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 8, 'ESA 010 - ENVIA FTP COM MONITORAR', NULL, NULL, 0, NULL),
('Linux', 9, 'ESA 011 - ENVIO FTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Linux', 10, 'ESA 012 - ENVIO FTP COM RENOMEIO ', NULL, NULL, 0, NULL),
('Linux', 11, 'ESA 013 - RECEBE FTP COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 12, 'ESA 014 - ENVIO FTP TRUNCAR NOME DO ARQUIVO', NULL, NULL, 0, NULL),
('Linux', 13, 'ESA 015 - RECEBE FTP TRUNCAR NOME DO ARQUIVO', NULL, NULL, 0, NULL),
('Linux', 16, 'ESA 016 - LITE MOVER COM ERROS', NULL, NULL, 0, NULL),
('Linux', 15, 'ESA 016 - LITE MOVER COM ERROS	', NULL, NULL, 0, NULL),
('Linux', 17, 'ESA 017 - ENVIO LITE COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Linux', 18, 'ESA 017 - RECEBE LITE COM MASCARA DE EXCLUSÃO', NULL, NULL, 0, NULL),
('Linux', 19, 'ESA 018 - ENVIO LITE TAMANHO KBYTES', NULL, NULL, 0, NULL),
('Linux', 20, 'ESA 018 - RECEBE LITE TAMANHO KBYTES', NULL, NULL, 0, NULL),
('Linux', 23, 'ESA 022 - ENVIO LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Linux', 24, 'ESA 022 - RECEBE LITE PERCORRE SUBPASTAS MANTENDO ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Linux', 25, 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 26, 'ESA 023 - LITE ENVIA SOBREPONDO NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 27, 'ESA 025 - ENVIO LITE VERSIONAR', NULL, NULL, 0, NULL),
('Linux', 28, 'ESA 025 - RECEBE LITE VERSIONAR', NULL, NULL, 0, NULL),
('Linux', 29, 'ESA 026 - ENVIO LITE /MONITORAR', NULL, NULL, 0, NULL),
('Linux', 30, 'ESA 026 - RECEBE LITE /MONITORAR', NULL, NULL, 0, NULL),
('Linux', 31, 'ESA 027 - ENVIO LITE COM COPIA', NULL, NULL, 0, NULL),
('Linux', 32, 'ESA 027 - RECEBE LITE COM COPIA', NULL, NULL, 0, NULL),
('Linux', 34, 'ESA 028 - ENVIO LITE COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 33, 'ESA 028 - ENVIO LITE COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 35, 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Linux', 36, 'ESA 029 - ENVIO LITE COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Linux', 39, 'ESA 032 - CXA COM MÁSCARA DE EXCLUSÃO', NULL, NULL, 0, NULL),
('Linux', 40, 'ESA 033 - CXA COM TAMANHO MIN / MAXIMO', NULL, NULL, 0, NULL),
('Linux', 42, 'ESA 037 - CXA PERCORRER SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 44, 'ESA 039 - CXA SOBREPOR LOCALMENTE', NULL, NULL, 0, NULL),
('Linux', 45, 'ESA 042 - CXA COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 47, 'ESA 044 - CXA COM COPIA NO CLIENT', NULL, NULL, 0, NULL),
('Linux', 48, 'ESA 045 - CXA BUSCA ARQUIVO NA RAIZ', NULL, NULL, 0, NULL),
('Linux', 49, 'ESA 046 - CXA COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Linux', 83, 'ESA 048 - ENVIO FTPS PERCORRENDO SUBPASTA', NULL, NULL, 0, NULL),
('Linux', 50, 'ESA 049 - SFTP COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Linux', 52, 'ESA 050 - SFTP TAMANHO MIN/MAX KB', NULL, NULL, 0, NULL),
('Linux', 54, 'ESA 051 - SFTP MOVER COM ERROS', NULL, NULL, 0, NULL),
('Linux', 56, 'ESA 052 - SFTP MOVER ARQ DA MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Linux', 61, 'ESA 055 - SFTP PERCORRER SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 63, 'ESA 056 - SFTP SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 65, 'ESA 058 - SFTP TMP NO DESTINO', NULL, 'Aprovada', 0, NULL),
('Linux', 67, 'ESA 060 - SFTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Linux', 69, 'ESA 061 - SFTP COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 71, 'ESA 062 - SFTP COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Linux', 73, 'ESA 063 - OFTP FORMATO ASCII 128 -> EBCDIC', NULL, NULL, 0, NULL),
('Linux', 76, 'ESA 064 - OFTP RECEBE COM RENOMEIO DE ARQUIVO', NULL, NULL, 0, NULL),
('Linux', 77, 'ESA 066 - OFTP COM CRLF ATIVO', NULL, NULL, 0, NULL),
('Linux', 79, 'ESA 067 - OFTP ENVIO COM COPIA', NULL, NULL, 0, NULL),
('Linux', 87, 'ESA 070 - FTPS SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 89, 'ESA 073 - FTPS COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Linux', 91, 'ESA 074 - FTPS MANTER ESTRUTURA DE PASTAS', NULL, NULL, 0, NULL),
('Linux', 93, 'ESA 076 - FTPS COM CRIPTOGRAFIA MD5', NULL, NULL, 0, NULL),
('Linux', 94, 'ESA 077 - FTPS COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 14, 'ESA 078 - RECEBE FTP COM COPIA REMOTA', NULL, NULL, 0, NULL),
('Linux', 97, 'ESA 079 -BANESTES (BNT 002)- ENVIA FTP', NULL, NULL, 0, NULL),
('Linux', 96, 'ESA 080  - RECEBE FTP EXPRESSAO REGULAR ', NULL, NULL, 0, NULL),
('Linux', 98, 'ESA 081 -  RECEBE FTP MULTIPLO DIRETORIO', NULL, NULL, 0, NULL),
('Linux', 99, 'ESA 082 - ENVIO LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA DOS SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Linux', 100, 'ESA 082 - RECEBE LITE PERCORRE SUBPASTAS SEM MANTER ESTRUTURA SUBDIRETORIOS', NULL, NULL, 0, NULL),
('Linux', 104, 'ESA 083 - ENVIA COM ANALYZER', NULL, NULL, 0, NULL),
('Linux', 106, 'ESA 085 - AGENDAMENTO RECEBE FTP', NULL, NULL, 0, NULL),
('Linux', 101, 'ESA 086 AGENDAMENTO - GOVSC ENVIA -> ESLOVENIA OFTP', NULL, NULL, 0, NULL),
('Linux', 107, 'ESA 087 - ALERTA ARQUIVO PARADO', NULL, 'Aprovada', 0, NULL),
('Linux', 84, 'ESA 088 - ENVIO FTPS PERCORRENDO SUBPASTA', NULL, NULL, 0, NULL),
('Linux', 51, 'ESA 089 - SFTP COM MASCARA DE EXCLUSAO', NULL, NULL, 0, NULL),
('Linux', 53, 'ESA 090 - SFTP TAMANHO MIN/MAX KB', NULL, NULL, 0, NULL),
('Linux', 55, 'ESA 091 - SFTP MOVER COM ERROS', NULL, NULL, 0, NULL),
('Linux', 62, 'ESA 092 - SFTP PERCORRER SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 64, 'ESA 093 - SFTP SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 66, 'ESA 094 - SFTP TMP NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 68, 'ESA 095 - SFTP COM COPIA LOCAL', NULL, NULL, 0, NULL),
('Linux', 70, 'ESA 096 - SFTP COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 72, 'ESA 097 - SFTP COM INTEGRIDADE MD5', NULL, NULL, 0, NULL),
('Linux', 74, 'ESA 098 - OFTP FORMATO EBCDIC -> ASCII', NULL, NULL, 0, NULL),
('Linux', 80, 'ESA 099 - OFTP RECEBE COM COPIA', NULL, NULL, 0, NULL),
('Linux', 88, 'ESA 100 - FTPS SOBREPOR NO DESTINO', NULL, NULL, 0, NULL),
('Linux', 92, 'ESA 101 - FTPS MANTER ESTRUTURA DE PASTAS', NULL, NULL, 0, NULL),
('Linux', 95, 'ESA 102 - FTPS COM RENOMEIO', NULL, NULL, 0, NULL),
('Linux', 108, 'ESA 105 - EXPURGO DE ARQUIVOS 35 DIAS', NULL, NULL, 0, NULL),
('Linux', NULL, 'ESA 107 - EXPURGO ARQ. MAIOR QUE 1000000KB', NULL, NULL, 0, NULL),
('Linux', 109, 'ESA 106 - EXPURGO DE ARQUIVOS 20 DIAS', NULL, NULL, 0, NULL),
('Linux', 110, 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 111, 'ESA 103 - ENVIA LITE PERCORRE SUBPASTAS', NULL, NULL, 0, NULL),
('Linux', 112, 'ESA 108 - ENCADEAMENTO DE REGRAS', NULL, NULL, 0, NULL),
('Linux', 113, 'ESA 109 - ENCADEAMENTO DE REGRAS', NULL, NULL, 0, NULL),
('Linux', 114, 'ESA - ? teste do NFS - Comportamento com um diretorio inexistente ', NULL, NULL, 0, NULL),
('Linux', 115, 'ESA 110 - ENVIO SSH CHAVE PUBLICA/PRIVADA', NULL, NULL, 0, NULL),
('Linux', 116, 'ESA 111 - RECEPCAO SSH CHAVE PUBLICA/PRIVADA', NULL, NULL, 0, NULL),
('Linux', NULL, 'ESA ? - Regra Analyzer', NULL, NULL, 0, NULL),
('Linux', NULL, 'ESA 092 - SFTP PERCORRER SUBPASTAS E ENVIAR PARA MULTIPLOS DIRETORIOS (ESPELHAR WINDOWS)', NULL, NULL, 0, NULL),
('Linux', NULL, 'ESA 096 - SFTP COM RENOMEIO E COPIA REMOTA (ESPELHAR)', NULL, NULL, 0, NULL),
('Linux', NULL, 'ESA 108 - ENCADEAMENTO DE REGRAS ( Espelhar )', NULL, NULL, 0, NULL);

SET FOREIGN_KEY_CHECKS = 1;